### ISSUE TITLE
Issue In CSC Explorer App

### ISSUE THREAD

**Issue by ryan-foamspace** [f-o-a-m/foam.developer#15]
all beacons disappear from the map if you conduct a search

**Comment by FergusDevelopmentLLC** [comment]
api query issue. i hope this is in the correct repo to post this.
This query is made to to the api in order to get all beacons, some are not returned.
https://api-beta.foam.space/beacon?lon_min=-1000&lat_min=-1000&lon_max=1000&lat_max=1000
For example...
Denver2, Coors Field, PointsDenver, beaconcore don't appear in the result, but are beacons:
https://bl.ocks.org/FergusDevelopmentLLC/0184791f202d731515ec9a315aaef1f7
